name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: |
                  cd client
                  npm i
            - name: Build React app
              run: |
                  cd client
                  CI=false npm run build
            - name: Setup key
              run: |
                  set -eu
                  mkdir "$HOME/.ssh"
                  echo "${{ secrets.key }}" > "$HOME/.ssh/key"
                  chmod 600 "$HOME/.ssh/key"
            - name: Deploy frontent
              run: |
                  cd client/dist
                  rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . pq@146.59.18.130:/var/www/rickmortytraineetestcase.pp.ua/html/
            - name: Deploy backend
              run: |
                  cd server
                  rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . pq@146.59.18.130:/var/www/api.rickmortytraineetestcase.pp.ua/
            - name: Run server
              uses: appleboy/ssh-action@master
              with:
                host: 146.59.18.130
                username: pq
                key: ${{ secrets.key }}
                script: |
                  cd /var/www/api.rickmortytraineetestcase.pp.ua/
                  npm i
                  npm start
