name: Deploy Server

on:
    push:
        branches:
            - main
        paths:
            - "server/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Deploy backend
              uses: burnett01/rsync-deployments@5.2.1
              with:
                switches:  -avzr --delete
                path: server/*
                remote_path: ${{ secrets.deploy_server_path }}
                remote_host: ${{ secrets.host }}
                remote_user: ${{ secrets.username }}
                remote_key: ${{ secrets.key }}

            - name: Setup backend
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.host }}
                username: ${{ secrets.username }}
                key: ${{ secrets.key }}
                script: |
                  cd ${{ secrets.deploy_server_path }}
                  npm i
